CREATE USER IF NOT EXISTS 'fllibrutti'@'%' IDENTIFIED BY '7zOhUgBtgNIqxSFZevvP5VH1GN75FrxgwFIdfpd2NJlYOM2dFBiIwBzFMQBtBCeD';

GRANT
  SELECT,
  INSERT,
  UPDATE,
  DELETE
ON appdb.* TO 'fllibrutti'@'%';

FLUSH PRIVILEGES;